@startuml
'https://plantuml.com/class-diagram

package personnages{
    interface Entite <<interface>>
    {
        + recevoirDegats(degats : Integer)
        + estVivant() : Boolean
        + attaquer(Entite cible) : String
        + getClasseArmure() : Integer
        + getNom() : String
        + getPV() : Integer
        + toString() : String
        + toStringDetails() : String
    }

    abstract class Personnage <<abstract>> implements Entite
    {
        - m_nom : String <<final>>
        - m_race : Race <<final>>
        - m_classe : String <<final>>
        - m_MAX_PV : Integer <<final>>
        - m_PV : Integer
        - m_force : Integer
        - m_dexterite : Integer
        - m_vitesse : Integer
        - m_initiative : Integer
        - m_armure : Armure
        - m_arme : Arme
        - m_inventaire : Equipement[*]

        ~ <<create>> Personnage(nom : String, race : Race, pv : Integer, inventaire : Equipement[*], classe : String)
        - {static} jetDes(nbLancers : Integer, nbFaces : Integer) : Integer
        + equiper(arme : Arme)
        + equiper(armure : Armure)
        + recevoirDegats(degats : Integer)
        + estVivant() : Boolean
        + getDistance() : Integer
        + attaquer(cible : Entite) : String
        + getClasseArmure() : Integer
        + getNom() : String
        + getPV() : Integer
        + toString() : String
        + toStringDetails() : String
        - afficherEquipement(Arme arme) : String
        - afficherEquipement(Armure armure) : String
        + resetPV()

    }

    enum Race <<enumeration>>
    {
        HUMAIN
        NAIN
        ELFE
        HALFELIN

        + toString() : String
    }

    class Guerrier extends Personnage
    {
        + <<create>> Guerrier(nom : String, race : Race)
        - {static} initInventaire() : Equipement[*]
    }

    class Clerc extends Personnage
    {
        + <<create>> Clerc(nom : String, race : Race)
        - {static} initInventaire() : Equipement[*]
    }

    class Magicien extends Personnage
    {
        + <<create>> Magicien(nom : String, race : Race)
        - {static} initInventaire() : Equipement[*]
    }

    class Roublard extends Personnage
    {
        + <<create>> Roublard(nom : String, race : Race)
        - {static} initInventaire() : Equipement[*]
    }

    class Monstre implements Entite
        {
            - m_id : Integer
            - m_espece : String
            - m_MAX_PV : Integer <<final>>
            - m_PV : Integer
            - m_force : Integer
            - m_dexterite : Integer
            - m_classeArmure : Integer
            - m_initiative : Integer
            - m_vitesse : Integer
            - m_porteeAttaque : Integer
            - m_nbLancers : Integer
            - m_nbFaces : Integer

            + <<create>> Monstre(ID : Integer, espece : String, PV : Integer, porteeAttaque : Integer, classeArmure : Integer, initiative : Integer, vitesse : Integer, force : Integer, dexterite : Integer, nbLancers : Integer, nbFaces : Integer)
            - {static} jetDes(nbLancers : Integer, nbFaces : Integer) : Integer
            - jetDesAttaque() : Integer
            + getClasseArmure() : Integer
            + getNom() : String
            + getPV() : Integer
            + recevoirDegats(degats : Integer)
            + estVivant() : Boolean
            + attaquer(cible : Entite) : String
            + toString() : String
            + toStringDetails() : String
        }
}

package equipement {
    abstract class Equipement <<abstract>>
    {
        # m_nom : String
        - m_classe : String
        # m_type : String
        # m_diminutionForce : Integer
        # m_augmentationForce : Integer

        ~ <<create>> Equipement(nom : String, classe : String)
        + getDiminutionVitesse() : Integer
        + getAugmentationForce() : Integer
        + getType() : String
        + <<abstract>> toString() : String
        + getClasse() : String
    }

    class Armure extends Equipement
    {
        - m_classe : Integer <<final>>

        + <<create>> Armure(nom : String)
        + toString() : String
    }

    class Arme extends Equipement
    {
        - m_nbLancers : Integer <<final>>
        - m_nbFaces : Integer <<final>>
        - m_nbPortee : Integer <<final>>

        + <<create>> Arme(nom : String, nbLancers : Integer, nbFaces : Integer, portee : Integer)
        + jetDes() : Integer
        + toString() : String

    }

}

Personnage "*" o--> "1..*\n - m_race" Race : est
Personnage "*" o--> "1..*\n - m_inventaire" Equipement : possède

class Donjon {
    - m_num : int
    - m_nb_joueurs : int
    - m_nb_montres : int
    - m_longueur : int
    - m_largeur : int
    - m_cases : Hashtable<String, int[][]


    +«Create» Donjon(num : int, joueurs : int, montres : int, longueur : int, largeurnom :int)
    +«Create» Donjon(num : int, joueurs : int, montres : int)
    +«Create» Donjon(num : int,joueurs : int, montres : int, longueur : int)

    +nommerCases() : void
    +remplirPlateau() : void
    +ordreDeJeu() : void
    +seDeplacer(perso : int) : void

}



@enduml