@startuml
'https://plantuml.com/class-diagram
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
skinparam style strictuml
hide empty members

class Main
{
    + {static} main( args:String[*] )
}

package personnages{
    interface Entite <<interface>>
    {
        + {abstract} recevoirDegats(degats : Integer)
        + {abstract} estVivant() : Boolean
        + {abstract} attaquer(Entite cible) : String
        + {abstract} getClasseArmure() : Integer
        + {abstract} getNom() : String
        + {abstract} getPV() : Integer
        + {abstract} toString() : String
        + {abstract} toStringDetails() : String
        + {abstract} getInitiative() : Integer
    }

    abstract class Personnage <<abstract>> implements Entite
    {
        - m_nom : String <<final>>
        - m_race : Race <<final>>
        - m_classe : String <<final>>
        - m_MAX_PV : Integer <<final>>
        - m_PV : Integer
        - m_force : Integer
        - m_dexterite : Integer
        - m_vitesse : Integer
        - m_initiative : Integer
        - m_armure : Armure
        - m_arme : Arme
        - m_inventaire : Equipement[*]

        ~ <<create>> Personnage(nom : String, race : Race, pv : Integer, inventaire : Equipement[*], classe : String)
        - {static} jetDes(nbLancers : Integer, nbFaces : Integer) : Integer
        + getNom() : String
        + equiper(arme : Arme)
        + equiper(armure : Armure)
        + recevoirDegats(degats : Integer)
        + estVivant() : Boolean
        + getDistance() : Integer
        + getInitiative() : Integer
        + attaquer(cible : Entite) : String
        + getClasseArmure() : Integer
        + getPV() : Integer
        + toString() : String
        + toStringDetails() : String
        - {static} afficherEquipement(arme : Arme) : String
        - {static} afficherEquipement(armure : Armure) : String
        + resetPV()
        + ajoutEquipement(arme : Arme)
        + ajoutEquipement(armure : Armure)
        - {static} afficherEquipement(armure : Armure, position : Integer) : String
        - {static} afficherEquipement(arme : Arme, position : Integer) : String
        + afficherInventaire() : String
        + tailleInventaire() : Integer
        + getEquipement() : Equipement

    }

    enum Race <<enumeration>>
    {
        HUMAIN
        NAIN
        ELFE
        HALFELIN

        + toString() : String
    }

    class Guerrier extends Personnage
    {
        + <<create>> Guerrier(nom : String, race : Race)
        - {static} initInventaire() : Equipement[*]
    }

    class Clerc extends Personnage
    {
        + <<create>> Clerc(nom : String, race : Race)
        - {static} initInventaire() : Equipement[*]
    }

    class Magicien extends Personnage
    {
        + <<create>> Magicien(nom : String, race : Race)
        - {static} initInventaire() : Equipement[*]
    }

    class Roublard extends Personnage
    {
        + <<create>> Roublard(nom : String, race : Race)
        - {static} initInventaire() : Equipement[*]
    }

    class Monstre implements Entite
    {
        - m_id : Integer <<final>>
        - m_espece : String <<final>>
        - m_MAX_PV : Integer <<final>>
        - m_PV : Integer
        - m_force : Integer
        - m_dexterite : Integer
        - m_classeArmure : Integer
        - m_initiative : Integer
        - m_vitesse : Integer
        - m_porteeAttaque : Integer <<final>>
        - m_nbLancers : Integer <<final>>
        - m_nbFaces : Integer <<final>>

        + <<create>> Monstre(ID : Integer, espece : String, PV : Integer, porteeAttaque : Integer, classeArmure : Integer, initiative : Integer, vitesse : Integer, force : Integer, dexterite : Integer, nbLancers : Integer, nbFaces : Integer)
        - {static} jetDes(nbLancers : Integer, nbFaces : Integer) : Integer
        - jetDesAttaque() : Integer
        + getNom() : String
        + getClasseArmure() : Integer
        + recevoirDegats(degats : Integer)
        + estVivant() : Boolean
        + getPV() : Integer
        + getInitiative() : Integer
        + attaquer(cible : Entite) : String
        + toString() : String
        + toStringDetails() : String
    }
}

package equipement {
    abstract class Equipement <<abstract>>
    {
        # m_nom : String
        - m_classe : String
        # m_type : String
        # m_diminutionForce : Integer
        # m_augmentationForce : Integer

        ~ <<create>> Equipement(nom : String, classe : String)
        + getDiminutionVitesse() : Integer
        + getAugmentationForce() : Integer
        + getType() : String
        + getClasse() : String
        + getNom() : String
        + {abstract} toString() : String
    }

    class Armure extends Equipement
    {
        - m_classe : Integer <<final>>

        + <<create>> Armure(nom : String)
        + getClasseArmure() : Integer
        + toString() : String
    }

    class Arme extends Equipement
    {
        - m_nbLancers : Integer <<final>>
        - m_nbFaces : Integer <<final>>
        - m_nbPortee : Integer <<final>>

        + <<create>> Arme(nom : String)
        + jetDes() : Integer
        + toString() : String

    }

}



package "jeu" {
    class Donjon {
        - m_num : Integer <<final>>
        ~ m_nb_monstres : Integer
        ~ m_nb_personnages : Integer
        - m_longueur : Integer
        - m_largeur : Integer
        - m_entites : Hashtable<Integer, Entite>
        - m_personnages : Hashtable<Personnage, Integer>
        - m_monstres : Hashtable<Monstre, Integer>
        - m_cases : Hashtable<String, Integer[*]>

        + Donjon(num : Integer, longueur : Integer, largeur : Integer)
        + Donjon(num : Integer)
        - initDonjon1()
        - initDonjon2()
        - initDonjon3()
        + ajoutPersonnage(e : Personnage)
        + ajoutMonstre(e : Monstre)
        + getListePersonnages() : Hashtable<Personnage, Integer>
        + getListeMonstres() : Hashtable<Monstre, Integer>
        + ajoutObstacle(position : String) : Boolean
        + ajoutEquipement(equip : Equipement, position : String)
        + getEquipementParId(id : int) : String
        + getId(entite : Entite) : Integer
        + positionner(e : Entite, position : String) : String
        + afficherIDentite()
        - getEntites() : Hashtable<Integer, Entite>
        - getNombreEntites() : Integer
        - existeCase(position : String) : Boolean
        - nommerCases()
        + getCases() : Hashtable<String, Integer[*]>
        - ordreDeJeu() : Entite[*]
    }

    class Narrateur {
            - m_pseudo : String
            + Narrateur(pseudo : String)
            + Narrateur()
            + getPseudo() : String
            + commenter(phrase : String) : String
    }

    class Tours {
               - m_nu : Integer <<final>>
               + Tours(num : Integer)
               + ajouterTourPersonnage(personnage : Personnage, donjon : Donjon, narrateur : Narrateur)
               + ajouterTourMonstre(monstre : Monstre, donjon : Donjon, narrateur : Narrateur)
    }
}


Personnage "*" o--> "1\n - m_race" Race : est
Personnage "*" o--> "1..*\n - m_inventaire" Equipement : possède
Personnage "1" *--> "1\n - m_arme" Arme : équipe
Personnage "1" *--> "1\n - m_armure" Armure : équipe
Personnage ..> Armure : <<uses>>
Personnage ..> Armure : <<call>>
Personnage ..> Arme : <<uses>>
Personnage ..> Arme : <<call>>
Personnage ..> Equipement : <<uses>>
Personnage ..> Equipement : <<call>>
Personnage ..> Entite : <<uses>>
Personnage ..> Entite : <<call>>

Monstre ..> Entite : <<uses>>
Monstre ..> Entite : <<call>>

Clerc ..> Arme : <<instanciate>>
Clerc ..> Armure : <<instanciate>>
Clerc ..> Equipement : <<uses>>

Guerrier ..> Arme : <<instanciate>>
Guerrier ..> Armure : <<instanciate>>
Guerrier ..> Equipement : <<uses>>

Magicien ..> Arme : <<instanciate>>
Magicien ..> Armure : <<instanciate>>
Magicien ..> Equipement : <<uses>>

Roublard ..> Arme : <<instanciate>>
Roublard ..> Armure : <<instanciate>>
Roublard ..> Equipement : <<uses>>



Donjon "*" *--> "1..*\n -m_entite" Entite : contient
Donjon "*" *--> "1..*\n -m_personnages" Personnage : contient
Donjon "*" *--> "1..*\n -m_monstres" Monstre : contient

Donjon ..> Arme : <<instanciate>>
Donjon ..> Armure : <<instanciate>>
Donjon ..> Equipement : <<uses>>
Donjon ..> Equipement : <<call>>
Donjon ..> Personnage : <<uses>>
Donjon ..> Personnage : <<call>>
Donjon ..> Monstre : <<uses>>
Donjon ..> Entite : <<uses>>
Donjon ..> Entite : <<call>>
Donjon ..> Entite : <<instanciate>>


Main ..> Personnage : <<call>>
Main ..> Clerc : <<instanciate>>
Main ..> Guerrier : <<instanciate>>
Main ..> Magicien : <<instanciate>>
Main ..> Roublard : <<instanciate>>
Main ..> Monstre : <<instanciate>>
Main ..> Donjon : <<instanciate>>
Main ..> Donjon : <<call>>
Main ..> Tours : <<instanciate>>
Main ..> Tours : <<call>>
Main ..> Narrateur : <<instanciate>>
Main ..> Equipement : <<uses>>
Main ..> Equipement : <<instanciate>>
Main ..> Equipement : <<call>>
Main ..> Armure : <<uses>>
Main ..> Arme : <<uses>>
Main ..> Armure : <<instanciate>>
Main ..> Arme : <<instanciate>>



Tours ..> Narrateur : <<uses>>
Tours ..> Narrateur : <<call>>
Tours ..> Donjon : <<uses>>
Tours ..> Donjon : <<call>
Tours ..> Personnage : <<uses>>
Tours ..> Monstre : <<uses>>
Tours ..> Personnage : <<call>>
Tours ..> Monstre : <<call>>
Tours ..> Equipement : <<instanciate>>
Tours ..> Equipement : <<call>>
Tours ..> Arme : <<instanciate>>
Tours ..> Arme : <<call>>
Tours ..> Armure : <<instanciate>>
Tours ..> Armure : <<call>>


@enduml